package enums;

public enum TypeReclamation {
    EN_ATTENTE,
    EN_COURS,
    PLAINTE,
    SUGGESTION,
     AUTRE,
     TRAITE,
     REMBOURSEE,
     RESOLUE,
     NON_RESOLUE,
     ANNULEE,
     CONFIRMEE,
     REJETEE,
     EN_ANALYSE,
     EN_RESOLUTION,
     RESOLUE_SANS_SUITE,
     RESOLUE_AVEC_SUITE,
     SUIVIE,
     ARCHIVEE,
     EN_ATTENTE_DE_REPONSE,
     REPONSE_FOURNIE,
     EN_COURS_DE_TRAITEMENT,
     TRAITEMENT_TERMINE,
     RECLAMATION,
    TRAITEE
}